name = "hefimer"
pages_build_output_dir = "./dist"
compatibility_date = "2026-06-19"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "HEFIMER_DB"
database_name = "hefimer-devices"
database_id = "cb102ff3-2a45-4e9a-a63f-0ea443aa0e5b"

[[kv_namespaces]]
binding = "PAIR_TOKENS"
id = "59d22e93bb214d76a39e1e7b81eb9303"
